# Summary
This document provides an overview of my current data analysis. It starts with an overview of all eleven CEE EU member states. Descriptive statistics display insights into the available data on anti-incumbent voting and emigration rates. I then continue by modelling emigration on incumbent vote change using a fixed effects model. Results show that an increase in emigration is associated with a decrease in incumbent vote share.

I then focus on the effects of service cuts in Poland and Romania. I examine these two CEE EU member states seperately. I again begin with descriptive statistics that provide an overview of the available data: population numbers, emigration rates, number of institutions per region and calculated ratios, e.g., number of children per school. Then I model the effects of service cuts on incumbent vote change, again using fixed effects models. I combine different independent variables in order to measure their combined effects. I also use the actual number of institutions instead of the ratio as independent variables, to see if results change. Finally, I truncate the data, removing outliers in an attempt to build models with higher validity.

Results partially align with what my theory predicts. In Poland, an increase in the number of children per school and an increase in the number of people per third place is associated with a decrease in incumbent vote share at NUTS2 level. In Romania, a decrease in the number of schools is associated with a decrease in incumbent vote share at NUTS3 level.

Next steps could be to take a region’s characteristic into account. E.g., differentiate between rural and urban regions, or regions that border neighbouring countries, in an attempt to group regions with similar trends. Another next step could be to take an incumbent party’s orientation into account, as this may have an effect on service cuts. I may also have to find an alternative for the remittances variable, which I include in my models to control for electoral volatility. Remittances are only available for an entire country and are automatically removed due to collinearity when creating fixed effects models.