## Results

add somewhere: “the associations we document are small in magnitude”

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Romania
anti_incumbent_vote <- ned_v_dem_cee %>% 
  dplyr::filter(country == "Romania") %>%
  dplyr::filter(prev_incumbent == T) %>%
  left_join(dplyr::select(ro, year, NUTS_ID, emigration_election_year_per_1000), by = c("year" = "year", "nuts2016" = "NUTS_ID")) %>%
  left_join(dplyr::select(ro_schools, -population), by = c("year" = "year", "nuts2016" = "NUTS_ID")) %>%
  left_join(dplyr::select(ro_hospitals, -population), by = c("year" = "year", "nuts2016" = "NUTS_ID")) %>% 
  left_join(dplyr::select(ro_third_places, -population), by = c("year" = "year", "nuts2016" = "NUTS_ID")) %>% 
  left_join(ro_volatility, by = c("year", "nuts2016")) %>% 
  left_join(ro_gdp, by = c("year" = "year", "nuts2016" = "NUTS_ID")) %>% 
  left_join(ro_unemployment, by = c("year", "nuts2016"))
```

```{r, child = 'model_spec_a.Rmd'}
```

```{r, child = 'model_spec_b.Rmd'}
```

```{r, child = 'hypotheses.Rmd'}
```