## Introduction
<!-- Central problem / puzzle that thesis will address -->
European Union (EU) member states in Central and Eastern Europe^[Bulgaria, Croatia, Czech Republic, Estonia, Hungary, Latvia, Lithuania, Poland, Romania, Slovakia and Slovenia] (CEE) have shown high levels of emigration in the past 20 years [@vorlanderMIDEM2021Emigration2021 7; @kyriaziPoliticsEmigrationEurope2023a 565]. Figure \ref{fig:net-migration-map} provides a geographic overview of net migration in Europe at subnational level. Accession to the EU has spurred on emigration, facilitated by the EU’s policy on Freedom of Movement (FoM). How does emigration affect political behaviour in sending countries? Theory tells us that emigration leads to service cuts, which in turn create grievances amongst the population that remains in sending countries [@dancygierEmigrationRadicalRight2022]. This population then turns against the incumbent party [@bowlerStrategicProtestVoting1992]. To better understand the dynamics between emigration and anti-incumbent voting behaviour, it is relevant to examine service cuts in detail.

```{r, child = 'map.Rmd'}
```

Before analysing the consequences of service cuts on voting behaviour in detail, it is important to state that emigration has a profound effect on sending countries [@thautEUIntegrationEmigration2009a]. Furthermore, emigration is a salient issue amongst the remaining population [@rice-oxleyEuropeSouthEast2019]. Finally, its effects on CEE EU member states are a blind spot in political science research [@kyriaziPoliticsEmigrationEurope2023a].

The United Nations estimated a population decline of 18 million people in Eastern Europe between the early 1990s and 2015, with emigration being the main reason for the decrease [@romeiEasternEuropeHas2016]. In one concrete example, Lithuania has lost a quarter of its population, with certain regions losing over 50% of residents [@ubarevicienePopulationDeclineLithuania2017a 58]. Intra-EU migration is driven by economic and labour market factors, as people emigrate to look for better job opportunities [@vasilopoulouOpportunityThreatPublic2019a 810].

Emigration has profound impacts on sending countries, e.g., population decline, lack of labour [@thautEUIntegrationEmigration2009a 220; @roosCompensatingEffectsEmigration2023a 187] or a change in the population’s ethnic profile [@vorlanderMIDEM2021Emigration2021 51]. Emigration affects individuals that are left behind. They feel a sense of loss and develop feelings of anger, distress and depression [@marchetti-mercerThoseEasilyForgotten2012a 388; @ivlevsEmigrationRemittancesSubjective2019 135].

Does emigration change the voting behaviour of the people left behind? Theory tells us that emigration creates grievances amongst the remaining voters [@dancygierEmigrationRadicalRight2022, 2]. I follow a definition of grievances provided by @flindersPartyPoliticsVs2022 [673], who see them to be negative emotions built around fear or anger. @dancygierEmigrationRadicalRight2022 show how these grievances lead to voting for populist and radical right (PRR) parties. I argue that these grievances can also cause a less radical shift in voting behaviour, e.g., an anti-incumbent vote. This argument is underlined by @bowlerStrategicProtestVoting1992, who tell us that grieving, dissatisfied voters are prone to casting a ballot against the incumbent [@bowlerStrategicProtestVoting1992, 489]. 

@dancygierEmigrationRadicalRight2022 focus solely on Sweden as a case study. I show that the phenomenon of emigration and voting behaviour change can also be applied to CEE EU member states. This is because the typical impacts of emigration, e.g., population decline or labour shortages, are not bound to a specific country.

Therefore, this thesis poses the following research question: Which emigration-induced service cuts have a negative impact on the sending country’s incumbent vote share?

<!-- Describe causal mechanism -->
@dancygierEmigrationRadicalRight2022 describe how emigration leads to voting for PRR parties. Regions with high emigration rates are prone to service cuts. These cuts cause grievances amongst the people left behind, who react by voting for PRR parties [@dancygierEmigrationRadicalRight2022, 2]. However, the authors do not show what exactly causes a change in voting behaviour and suggest that future research should look into which service cuts eventually lead to PRR voting [@dancygierEmigrationRadicalRight2022, 35].

This thesis will examine three types of emigration-induced service cuts that can cause grievances. These cuts are school closures, hospital closures and closures of “third places”, i.e., places that foster community building, such as cafés, bars and restaurants. I put forward the idea that these service cuts cause grievances that in turn lead to an anti-incumbent vote.

<!-- Why is it worth studying? -->
There is a research gap when it comes to understanding the political repercussions of emigration on sending regions [@kyriaziPoliticsEmigrationEurope2023a 564]. This is all the more surprising since, globally speaking, the people who do *not* emigrate outnumber the people who do [@marchetti-mercerThoseEasilyForgotten2012a 378]. Therefore, in the specific case of the EU, FoM should be studied not only from the view of a right to enter, but also as a right to exit [@bruzeliusTakingEmigrationSeriously2021a 35] and the consequences this has.

FoM, a foundational aspect of the EU, affects politics in both receiving *and* in sending countries [@kyriaziPoliticsEmigrationEurope2023a 563]. Examining the effects of FoM, particularly on voting behaviour, in regions experiencing high emigration levels is crucial in explaining the impact EU accession has on new member states like Croatia and other CEE countries. This analysis will provide insights into the implications of future European integration, e.g., when further Balkan states or Ukraine join the EU.^[2023 State of Union address by EU Commission President Ursula von der Leyen at 1h 5min 41sec (https://www.youtube.com/live/3CodB7iohUI?si=xe06mS4q8qjeJYpi&t=3941, retrieved 6 October 2023)]

<!-- Thesis Setup -->
This thesis is set up as follows. I begin with a literature review, looking into existing findings and theory behind the effects of emigration on voting behaviour. Next, following @dancygierEmigrationRadicalRight2022’s approach, I put forward hypotheses that posit an association between emigration-induced service cuts and incumbent support. Based on the theory, I expect service cuts to reduce incumbent support.

I continue by explaining how I operationalise service cuts, emigration and incumbent support based on data provided by Eurostat and the statistical offices of Poland and Romania. Based on this, I first examine possible associations between external emigration, incumbent support and service cuts. I work with subnational NUTS^[The NUTS classification (_Nomenclature des unités territoriales statistiques_) is a geographic classification standard established by Eurostat, the EU’s statistical office. It is hierarchical system based on three levels of detail, with level NUTS3 being the lowest level, i.e., the level with the smallest geographic regions (https://ec.europa.eu/eurostat/web/nuts/overview, retrieved 23 January 2024)] level data, as different regions within countries have different levels of emigration and service cuts. This approach allows for more differentiated measurements.

The results from the first step merit further research into the specific case of Romania. Thus in a next step, I build two-way fixed effects linear regression models to uncover an association between incumbent support and service cuts in Romania. The results imply that the hypotheses must be rejected, however there are hints at a possible association between emigration-induced school closures and loss of incumbent support.

The thesis concludes with interpreting the results in the context of European integrations, describes the thesis’ limits and shows possible avenues of further research.
