### Operationalising DV and IV

#### Dependent Variable: Incumbent Vote Share Change
In my analysis, the dependent variable is the change in incumbent vote share. To operationalise this, I pick two consecutive national parliamentary elections, referred to as E0 and E1. Following the incumbent definition provided in paragraph X (TO DO), I label each party as either incumbent or non-incumbent at E0. Next, I calculate the change in the party's vote share between E0 and E1. A positive value indicates an increase in support, a negative value signifies a loss in vote share and thus less support.

#### Independent Variables: Service Cuts
I operationalise service cuts based on the assumption that a person's experience of a service is influenced by the user density per service point (e.g., schools, hospitals). As more people use a single service point, individual experiences tend to deteriorate. This is due to factors like diminished individual attention, overstretched personnel and longer waiting times. A service cut, such as the closure of a hospital, typically results in an increased number of users at remaining facilities, leading to a perceived decrease in service quality. By using the ratio of people per institution, I aim to capture the perceived quality of a service. This offers a more nuanced understanding than merely counting the number of institutions. This approach acknowledges that the development of grievances, influenced by service quality, can eventually impact voting behavior.

Service cuts are operationalized by examining the average changing ratio of institutions to their respective target audiences between two elections. This can be best understood through an example. The number of primary-aged children per school in a specific NUTS region in a given year equals the ratio. This ratio varies annually and is recorded in the “yearly change” column. To calculate the average change between two elections, I average all the “yearly change” values starting from the year of the last election and ending one year before the next election.

- TO DO: Insert example table

As described in the Theory section (TO DO: add reference to page nr?), the three service cuts under examination are school and hospital closures, as well as shutting down “third places”. I operationalise these service cuts as the ratio of primary school aged children per primary school, number of people per hospital and number of people per “third place” in a NUTS region.

My focus on primary schools is based on the assumption that their closures have a stronger impact compared to the closure of vocational or high schools, for the following reasons. Primary schools act as community centers for young families. Their closure affects not just the pupils but also their families and the wider community, disrupting established community networks. The closure of a local primary school can lead to longer commute times for school children and their accompanying parents, as they are compelled to send their children to more distant schools as local schools have closed. This increase in travel time can foster negative sentiments towards the closure and contribute to the development of grievances.

<!-- explain somewhere here that this is my attempt at preventing reverse causality, ie. that emigration cause service cuts and NOT service cuts cause emigration; i can argue because I'm using the time element, as in I'm calculating the difference from one time point to the next -->

#### Control Variables
In order to islolate the effect of service cuts on incumbent support, I control for emigration, electoral volatility and economic performance within a NUTS region.

##### Emigration Rate
When operationalising emigration rate, I base my approch on @dancygierEmigrationRadicalRight2022. I only take the number of departures from a NUTS region into account, in order to isolate the effect of emigration from other demographic factors that may influence the association between population decline and incumbent support [@dancygierEmigrationRadicalRight2022 5]. I only take external emigration into account, i.e., migration abroad, and discard internal emigration from one region into another. I focus on this because I aim to capture the effect of country’s accession into the EU and with it, its gain to the EU’s Freedom of Movement. I operationalise emigration rate as the sum of emigrants in a region between two elections [@dancygierEmigrationRadicalRight2022 17], divided by the average population in that region between the elections. I then multiply this value by 1000 in order to get the value per 1000 inhabitants. Table X displays this calculation with an example (TO DO add table). This form of operationalisation aims at capturing the outflow of people and its impact on the remaining inhabitants. I use the sum of all emigrants from a region between two elections in order to capture the extent of the effect of emigration that a voter may feel when they cast their ballot. Averaging the population is a means to find a middle value in the same time period, in thic case between two elections. Finally, I divide by the population and times by 1000 in order to make the rate comparable between regions.

<!-- operationalisation of volatility using pedersen index -->
I operationalise electoral volatility by calculating the Pedersen Index [@pedersenElectoralVolatilityWestern1979] for each NUTS region in every election that data are available for. The Pedersen Index provides a value between 0 and 100 representing the electoral volatility from one election to the next. A value of 0 means there is no change in party vote share between elections. A value of 100 means the opposite, that all parties from the previous election lose all vote share in the next election and are replaced with new parties. Using data from @schraffEuropeanNUTSlevelElection2023, I calculate the Pedersen Index in R using the politicsR package [@denissonsilvaSilvadenissonPoliticsRV02023]. Table \@ref(tab:ro-pedersen-example) shows electoral volatility between the 2008 and 2012 parliamentary elections in an examplary Romanian NUTS region.

- an important note about the @schraffEuropeanNUTSlevelElection2023 data
- Parties receive a unique ID based on @doringPartyFactsDatabase2019
- Defining a single party over time has its own caveats [@doringPartyFactsDatabase2019 101]
- Within the scope of this thesis, I deem it sensible to follow the party coding provided by @schraffEuropeanNUTSlevelElection2023.
- This results in, e.g., two seperate parties having their own unique ID at election E0. If these two parties then span together to form a coalition government after the next election (E1), this results in a third, new ID that is not linked to the first two IDs.

- This can be best explained with an example in Table \@ref(tab:ro-pedersen-example).
- The National Liberal Party (ID: 481) reached 23.83\% of the vote in the 2008 election in Bihor County, the Alliance PSD+PC (ID: 6153) got 17.72\% of the vote.
- These parties formed the Social Liberal Union (ID: 5941) in 2011^[Source: https://en.wikipedia.org/wiki/National_Liberal_Party_(Romania)#Transition_from_USL_to_ACL_and_third_governing_experiences_(2010%E2%80%932020), retrieved 27 January 2024], the name under which they competed in the 2012 election.
- Due to this merge, the National Liberal Party and the Alliance PSD+PC have an election result for the 2008 election and zero percent vote share for the 2012 election. On the other hand, the Social Liberal Union has zero percent vote share in the 2008 election and 49.25\% vote share in the 2012 election.
- Treating party merges this way will result in a Pedersen Index that is too high, as parties that merge do not truly lose their entire electoral share
- It may be debateable that voters could consider a new alliance of existing parties to be a novel party of sorts. However, a more compelling argument in the context of this thesis is that manually coding party merges and separation would go beyond the scope of this paper. Thus using the unique party IDs provided by @schraffEuropeanNUTSlevelElection2023 seems the most sensible approach for the time being.

```{r ro-pedersen-example, echo=FALSE, message=FALSE, warning=FALSE, results='asis', fig.cap="ro pedersen example"}
ro_volatility_2012 <- ro_volatility_table %>% 
  dplyr::select(-y_2004, -y_2016) %>% 
  group_by(nuts2016) %>% 
  dplyr::filter(!is.na(y_2008) | !is.na(y_2012)) %>% 
  mutate(y_2008 = case_when(is.na(y_2008) == T ~ 0,
                            T ~ y_2008)) %>% 
  mutate(y_2012 = case_when(is.na(y_2012) == T ~ 0,
                            T ~ y_2012)) %>% 
  mutate(volatility_2012 = volatility(y_2008, y_2012)) %>% 
  dplyr::filter(nuts2016 == "RO111") %>% 
  ungroup(nuts2016) %>% 
  dplyr::select(partyfacts_id, y_2008, y_2012) %>% 
  mutate(y_2008 = round(y_2008, 2)) %>% 
  mutate(y_2012 = round(y_2012, 2)) %>% 
  arrange(-y_2008)

kable(ro_volatility_2012,
      caption = "Displaying how electoral volatiltiy is calculated using the Pedersen Index in Bihor County, Romania (RO111)",
      format = "latex", booktabs = TRUE) %>% 
  kable_styling(font_size = 9) %>% 
  add_footnote("RO111 has a Pedersen Index of 73.5 in the year 2012. Some party identifiers are missing because they are deemed irrelevant by @bederkePartyFactsVersion2020 [@schraffEuropeanNUTSlevelElection2023 572]. Full party name can be accessed through partyfacts.herokuapp.com/data/partycodes/Party ID/", notation="alphabet")
```

<!-- operationalisation of economic performance -->
- i operationalise a region’s economic performance using two variables
- the first is a region’s yearly gross domestic product at current markets prices in Euros per inhabitant
- these data are provided by eurostat^[https://ec.europa.eu/eurostat/databrowser/view/nama_10r_3gdp__custom_9030433/default/table?lang=en (retrieved 16 December 2023)]
- i use the GDP per capita as a general indicator for a region’s economic performance under the assumption that this value captures the overall economic performance in a way that is comparable across different regions within a country
- the second is a region’s unemployment rate, provided by the romanian statistical agency^[Variable SOM103A: Unemployment rate by gender, macroregions, development regions and counties (http://statistici.insse.ro:8077/tempo-online/#/pages/tables/insse-table, retrieved 19 January 2024)]
- I use the unemployment rate as an indicator for the overall economic mood in a region. The unemployment rate is a common indicator to judge the incumbent party’s economic performance by. It is widely recognised and used by voters and the media alike.

<!-- incorporate this, but rewrite for it to fit into “economic performance” -->
- @powellRevisitingElectoralVolatility2014 [139, 143] show that economic downturns, specifically shifts in GDP since the fall of Communism, lead to a higher likelihood of the electorate switching to a new party. 
- This observation aligns with @bertusGeographyElectoralVolatility2022 [77]’s study, highlighting that in smaller Hungarian settlements, socioeconomic dynamics and labour market conditions explain electoral shifts.
