### Research Design
- I differentiate between internal and external migration and focus on the latter, as I want to examine the effect of the EU’s FoM on emigration and voting behaviour.
- I will measure the effect of service cuts on a subnational, NUTS3 level, data permitting. I do this for the following two reasons. First, measuring subnational regions instead of countries will increase sample size and thus provide more accurate results. Second, regions within countries have different levels of emigration (see Figure TO DO: line chart of PL and RO NUTS emigration), allowing for differentiated measurements.

### Overview of available data, how it was collected and transformed

<!-- Ideal Data Situation -->
- In order to measure an effect of a country joining the EU, it would be ideal to have longitudinal data that starts before a country’s accession into the EU and continues up until 2019, after which the COVID-19 pandemic interferes with the possibility of emigration.
- however, these data are not fully available, as displaayed in Table X (TO DO: data availability table)

<!-- Incumbent Party -->
The V-Party Dataset [@staffan.i.lindbergVPartyDatasetV22022] provides information on which parties are in or support the government.^[Variable “v2pagovsup”: Does this party support the government formed immediately after this election? (Codebook p. 24)]. I manually add further elections and parties to the data in order to minimise missing values and obtain a more complete picture of anti-incumbent voting. I retrieve data on whether a party is incumbent or not based on the documented electoral history on their Wikipedia page.^[E.g., https://en.wikipedia.org/wiki/Greater_Romania_Party#Electoral_history (retrieved 15 January 2024)] Furthermore, I adjust the V-Party Dataset and categorise parties that show government support leading up to an election as incumbent, even if they are outside of government. I do this because I assume a citizen who wants to cast an anti-incumbent vote will vote against any party that supports or sypmathises with incumbent parties.

<!-- Election results -->
Subnational election results are provided by the European NUTS-level election dataset [@schraffEuropeanNUTSlevelElection2023]. I remove EU parliament elections from the data, leaving only national parliament election results. I also remove votes cast from abroad, parties named “Other” and elections before the year 1994 and after 2020. I calculate a party’s vote share by dividing the number of received votes by the total number of votes cast in the region, then multiply this by 100 to receive the regional vote share in percent. In a next step, I calculate a party’s regional vote change between two consecutive elections.

Using unique party IDs, I can combine the V-Party Dataset with the European NUTS-level election dataset. This combined dataset shows the regional vote change of incumbent parties.

(TO DO: Show snippet of n_v_dem_cee)

- Anti-incumbent vote: NED and V DEM

<!-- Election years -->
The years in which national parliamentary elections were held are retrieved from Wikipedia^[E.g., https://en.wikipedia.org/wiki/2019_Polish_parliamentary_election or https://en.wikipedia.org/wiki/2016_Romanian_parliamentary_election (both retrieved 15 January 2024)]

- External emigration for all CEE
Data on external emigration are provided by national statistical offices. I use the sum of people moving abroad from a NUTS region in a year. I choose this crude value because it carries more validity when it comes to measuring the impact of emigration than, e.g., net migration, which uses the difference between immigration and emigraiton.

<!-- Service Cuts -->
Data on service cuts at regional levels are provided by national statistical offices.

<!-- Service Cuts in Poland -->
The Polish government agency “Statistics Poland”^[https://bdl.stat.gov.pl/bdl/start, retrieved 20 November 2023] provides data on the number of primary schools at NUTS2 level^[Variable P1781: Primary schools for children, youth, and adults, by governing authority (https://bdl.stat.gov.pl/bdl/dane/podgrup/tablica, retrieved 20 November 2023)] and the size of the primary school population^[Variable P1341: Population by singular age and sex (https://bdl.stat.gov.pl/bdl/dane/podgrup/tablica, retrieved 20 November 2023)].

“Statistics Poland” also provides NUTS2 level data on the number of hospitals ^[Variable P2452: General hospitals (https://bdl.stat.gov.pl/bdl/dane/podgrup/tablica. retrieved 24 November 2023)] as well as the number of third places. ^[Variable P2505: Number of catering estabilishments [sic] (https://bdl.stat.gov.pl/bdl/dane/podgrup/tablica, retrieved 27 November 2023)]

<!-- Service Cuts in Romania -->
The Romanian government agency “National Institute of Statistics”^[https://insse.ro/cms/en, retrieved 15 January 2024] hosts data on the number of primary and lower-secondary schools^[Variable SCL101A: Education units, by categories of units, ownerships, macroregions, development regions and counties (http://statistici.insse.ro:8077/tempo-online/#/pages/tables/insse-table, retrieved 15 December 2023)] and the size of the population enrolled in these schools^[Variable SCL103E: Enrolled population, by level of education, urban/ rural area, macroregions, development regions and counties (http://statistici.insse.ro:8077/tempo-online/#/pages/tables/insse-table, retrieved 15 December 2023)]. Furthermore, the Institute also counts the number of hospitals^[Variable SCL101A: Sanitary units, by category of units, ownerships, macroregions, development regions and counties (http://statistici.insse.ro:8077/tempo-online/#/pages/tables/insse-table, retrieved 18 December 2023)] and third places.^[Variable INT101U: Active local units, by activity of national economy at level of CANE Rev.2 classes, size classes of number of employees, macroregions, development regions and counties (http://statistici.insse.ro:8077/tempo-online/#/pages/tables/insse-table, retrieved 15 December 2023)]

<!-- Romanian Classrooms as a proxy -->
As Figure X shows (TO DO), there is an inexplicable large drop in the number of Romanian schools in the early 2000s. I assume that along with schools closings, the Romanian “National Institute of Statistics” changed the way they counted single school entities. To counter this problem, I use the number of classrooms in primary and lower-secondary schools^[Variable SCL105C: Classrooms (school cabinets/amphiteaters), by level of education, macroregions, development regions and counties (http://statistici.insse.ro:8077/tempo-online/#/pages/tables/insse-table, retrieved 8 January 2024)] as a proxy for the number of school buildings. Figure X displays the number of classrooms, whereby a decrease is visible across most regions, but no sudden drop occurs (TO DO). Thus I assume the number of classrooms to be a more meaningful variable for Romanian schools closings than the number of school buildings.