## Literature Review and Theory

<!-- Emigration affects voting behaviour and electoral outcomes. It changes the electoral composition and influences the people left behind. -->
The impact of emigration on voting behaviour and electoral outcomes varies by time and location. A variety of studies have explored this phenomenon, ranging from 19th-century Sweden [@karadjaExitVoicePolitical2019 2] to early 21st-century Mexico [@pfutzeClientelismSocialLearning2014a 295].

Emigration can affect electoral outcomes in two ways. First, emigration can change the composition of the electorate. @limElectoralConsequencesInternational2023 [39] shows that emigrants from CEE are disproportionately younger, cosmopolitan and politically progressive, resulting in a remaining population that is older and more conservative. As a result, electoral results are more likely to be conservative, too.

Second, emigration can affect the voting behaviour of the people left behind. This effect can be indirect and direct.

The *indirect* effect occurs when emigration alters a voter’s overall well-being. Family members or neighbours of emigrants have a higher life satisfaction and budget easing through remittances, but suffer from more depression and stress [@ivlevsEmigrationRemittancesSubjective2019 135] and are more prone to anger and distress [@marchetti-mercerThoseEasilyForgotten2012a 388], caused by the departure of people close to them. A voter’s overall well-being will, amongst other aspects, influence their perception of parties and candidates and thus their voting behaviour.

There are multiple *direct* effects of emigration on political behaviour. A wide range of literature explains how emigration causes a decrease in political interest. This can be triggered by a decrease in political mobilisation and collective action [@sellarsEmigrationCollectiveAction2019a 1220], a decrease in civic engagement [@goodmanExitLeavingPolitical2008 172; @bravoEmigrationPoliticalEngagement2009], opposing voices leaving and thus resulting in a more incumbent supporting electorate [@petersEmigrationPoliticalContestation2022a 14] or through a loss of political actors [@limElectoralConsequencesInternational2023 44].

Despite this decrease in political interest, some of the remaining electorate still votes. If the number of people casting their ballot decreases, then it becomes all the more important to understand how the remaining voters are affected by emigration and thus how they cast their ballot.

One concrete example why this is important is shown by @barsbaiEffectLaborMigration2017a [36], who reveal a negative effect between emigration and votes for the Communist Party in the Moldovan elections of 2009 and 2010. These elections brought significant political change to the ex-soviet country [@barsbaiEffectLaborMigration2017a 41], because voters cast a ballot against the Communist Party, who had gained electoral power in previous elections. Voters turned against the Communist Party because returning emigrants brought western social norms and political preferences to Moldova [@barsbaiEffectLaborMigration2017a 66]. These preferences then diffused amongst the electorate.

<!-- Emigration benefits populist and radical right parties in Sweden (Dancygier et al., 2022) -->
A further reason why the effects of emigration on voting behaviour are important is its implications on voting for populist and radical right (PRR) parties [@dancygierEmigrationRadicalRight2022 34; @limElectoralConsequencesInternational2023 56; @heroldSchrumpfendeRegionenFrustrierte2020 19]. 

@dancygierEmigrationRadicalRight2022 [35] uncover a correlation between emigration and the rise of PRR parties. The authors suggest that emigration decreases an area’s quality of life, e.g., through cuts in public services. These service cuts create grievances amongst voters. These grievances then affect voting behaviour. Grieving voters turn against incumbents and cast a ballot for PRR parties.

<!-- Emigration doesn't have to lead to PRR voting, can also just simply change voting behaviour in general: Pt. 1 -->
However, there are several reasons why voting for PRR parties can be questioned in the chain of events presented by @dancygierEmigrationRadicalRight2022. Grievances caused by emigration do not necessarily have to lead directly to a vote for PRR parties. I argue in favour of a less drastic outcome, namely that emigration-induced grievances alter voting behaviour in general. 

Emigration from CEE EU member states is primarily caused by economic factors [@vasilopoulouOpportunityThreatPublic2019a 810]. This is relevant because understanding the reason *why* people emigrate helps to explain the impact of emigration on the sending country [@kapurPoliticalEffectsInternational2014a 488]. If one of the impacts caused by *economic* emigration is grievances, then I assume that these grievances will be linked to economic factors and less to, say, personal or family matters, e.g., as described by @ivlevsEmigrationRemittancesSubjective2019 [135]. Then, if these grievances are of an economic nature, I assume that they are more likely to be voiced in the public realm than grievances stemming from personal issues. This public realm can be the ballot box, and a person voicing their emigration-induced grievances can manifest itself as a change in voting behaviour. Thus I assume that emigration-induced grievances can affect voting behaviour in general, and do not necessarily have to lead directly to support a PRR party.

<!-- Emigration doesn't have to lead to PRR voting, can also just simply change voting behaviour in general: Pt. 2 -->
I argue that this general change in voting behaviour manifests itself as a decrease in incumbent support for the following reasons.

\label{passage:retrospective-vote} First, voters evaluate a government’s past performance and their policy outcomes [@keyResponsibleElectorateRationality1966a 35, 58–59, 61]. They vote retrospectively and their voting behaviour is influenced by salient issues [@keyResponsibleElectorateRationality1966a 73], such as the described service cuts. These cuts affect citizens’ daily lives and cause grievances, giving the incumbent party a poor performance record. Grieving voters that are dissatisfied with the incumbent party will not support them in the next election [@bowlerStrategicProtestVoting1992, 489].

Second, @vorlanderMIDEM2021Emigration2021 [36] shows that far-right parties only profit from emigration in economically weak regions. By only examining votes in favour of PRR parties, I would exclude the effect of emigration on economically stronger regions.

Third, non-extreme parties, e.g., mainstream opposition parties, may also benefit from emigration. There are several possible reasons for this. One, a voter can critique the incumbent government or status quo parties if emigration becomes politicised [@vorlanderMIDEM2021Emigration2021 91]. Two, voters receive remittances through emigrated family members, which realign their party preferences closer to their personal ideological preferences [@pfutzeDoesMigrationPromote2012a 161]. This realignment does not necessarily have to lead to voting for an extreme party. Fourth, voters cannot cast a ballot for an extreme party if there is no such party competing.

In sum, I agree in principle with the causal chain put forward by @dancygierEmigrationRadicalRight2022. However, based on the arguments above, I alter its final step from voting for PRR parties to a more general anti-incumbent vote.

<!-- RQ following Dancygier et al. (2022) and my contribution -->
Returning to the start of the causal chain described above, it remains unclear which service cuts cause grievances that subsequently change voting behaviour [@dancygierEmigrationRadicalRight2022 35]. This presents an opportunity to explore and identify specific service cuts. This thesis aims to identify which emigration-induced service cuts fit into the mechanism described by @dancygierEmigrationRadicalRight2022. This leads to the following research question: Which emigration-induced service cuts decrease incumbent support?

By answering this question, my thesis contributes to literature on emigration and its effects on voting behaviour. Furthermore, this thesis argues that future research should incorporate the causal mechanism proposed by @dancygierEmigrationRadicalRight2022 and take the emigration-induced service cuts identified here into account.

<!-- service cuts to be examined -->
@dancygierEmigrationRadicalRight2022 [2] state that emigration is linked to service cuts such as schools and business closures. Also, emigration strains the healthcare system. \label{passage:theory-service-cuts} Based on this, I assume that emigration has a negative effect on the number of schools, the number of hospitals and the number of “third places”, i.e., local "informal public gathering places" such as cafés, bars and restaurants that foster community building [@oldenburgGreatGoodPlace1999 16]. Following @dancygierEmigrationRadicalRight2022, a decrease in the number of these institutions will cause grievances amongst the remaining population for the following reasons.

<!-- schools -->
Schools contribute towards community feeling [@sagemanSchoolClosuresRural2022 964]. Closing a school will reduce a community's cohesion and negatively impact the lives of families with school-aged children. I assume that younger children, i.e., primary school aged children, to be more strongly affected by such a disruption than older children in secondary school or above. This is why I focus on primary schools. Furthermore, primary school children are more likely to be reliant on their parents or guardians when travelling to school. Thus closing a primary school will also impact people close to an affected child, as families must travel further to reach a school. Children can also be affected by a school closure that is not their own, as children from a closed school must be redistributed amongst existing schools, leading to an increase in children per class.

<!-- hospitals -->
Because emigrants tend to be younger [@limElectoralConsequencesInternational2023 39], the remaining population is likely to be older (see also Figure \@ref(fig:pl-ro-population)). Elderly citizens are more reliant on hospitals, thus I argue that a hospital closure can cause distress and grievances amongst the population. Hospital closures in CEE are spurred on by the emigration of medical professionals [@vorlanderMIDEM2021Emigration2021 13; @walkerRomanianHospitalsCrisis2019]. 

To underline the importance of school and hospital closures, @dancygierEmigrationRadicalRight2022 [32] show how newspapers report on such closings in Swedish regions that experience high levels of emigration. This indicates that there may exist a link between school and hospital closures and grievances.

<!-- third places -->
Schools and hospitals are services predominantly made available by the state. In contrast, third places are provided by the private sector. I make the assumption that the number of third places depends on demand in the population. Third places are institutions frequented by different parts of the population, thus an emigration-induced decrease of the overall population will lead to a decrease in demand for third places. This decrease in demand can lead to a decrease in supply, thus leading to closures of third places. These closings can erode a communal sense of belonging and push people towards populist parties [@boletDrinkingAloneLocal2021 1653].

### Hypotheses
I assume a decrease in the number of institutions, e.g., less schools, to indicate an increase in service cuts. Thus as a general relation, I expect an increase in service cuts (independent variable) to be associated with a decrease in incumbent support (dependent variable). This leads to the following three hypotheses:

**H1**: Service cuts to primary schools lead to a decrease in incumbent support.

**H2**: Service cuts to hospitals lead to a decrease in incumbent support.

**H3**: Service cuts to third places lead to a decrease in incumbent support.

### Case Study Selection
@dancygierEmigrationRadicalRight2022 focus on emigration and its effect on voting behaviour in Sweden. Their focus stems from the availability of detailed Swedish data [@dancygierEmigrationRadicalRight2022 34]. The authors also show that emigration has a significant positive effect on PRR party support across Europe [@dancygierEmigrationRadicalRight2022 34]. This hints at the possibility that the mechanism they put forward can also be applied to other European states. Thus I set out to examine CEE EU member states, as these countries have high emigration rates [@vorlanderMIDEM2021Emigration2021 7; @kyriaziPoliticsEmigrationEurope2023a 565], spurred on by the EU’s FoM. Emigration in CEE has not been studied in detail [@kyriaziPoliticsEmigrationEurope2023a 566]. Here exists an opportunity to measure the political impact of FoM on sending countries. This is an understudied aspect of FoM, as political science research often focuses on the *immigration* that FoM causes and its impact on *receiving* countries [@kyriaziPoliticsEmigrationEurope2023a 563].

Specifically in this thesis, I focus on Poland and Romania. These countries provide accessible data on the above defined service cuts through their respective statistical offices. They are also notable as CEE EU member states, as they have displayed the highest absolute numbers of yearly emigration since 2010.^[Eurostat Variable _migr_emi1ctz_: Total number of long-term emigrants leaving from the reporting country during the reference year (https://ec.europa.eu/eurostat/databrowser/view/tps00177__custom_9431582/default/table?lang=en, retrieved 19 January 2024)] For these reasons and to remain within the scope of this thesis, I aim to measure the potential impact of emigration-induced service cuts on incumbent support in both Poland and Romania.

### Control Variables
In order to isolate the effect of service cuts on incumbent support, I control for the following variables that may also affect incumbent support. First, I control for general electoral volatility. CEE states show higher levels of electoral volatility than states in Western Europe, Latin America or the United States [@epperlyInstitutionsLegaciesElectoral2011 831]. Incumbent parties suffer the most under this electoral volatility [@bochslerThreeStagesIncumbency2019 1]. 

Second, I control for a region’s economic performance. I do this under the assumption that voters punish or reward incumbent parties based on the economic conditions voters find themselves in. Good economic performance leads to incumbent support, bad performance leads to voters punishing the incumbents [@lewis-beckEconomicDeterminantsElectoral2000 183]. In the specific context of CEE, @powellRevisitingElectoralVolatility2014 [139, 143] show that economic downturns, specifically shifts in GDP since the fall of Communism, increase the likelihood of the electorate switching to a new party. This observation aligns with @bertusGeographyElectoralVolatility2022 [77], who find that in smaller Hungarian settlements, socio-economic dynamics and labour market conditions explain electoral shifts.
