### Truncating Data
…

```{r echo=FALSE, message=FALSE, warning=FALSE}
hist(anti_incumbent_vote$vote_change, breaks = 50)
summary(anti_incumbent_vote$vote_change)

ggplot(anti_incumbent_vote) +
  geom_histogram(aes(x = vote_change), binwidth = 1) +
  # xlim(-1,1) +
  theme_minimal()

ggplot(anti_incumbent_vote) +
  geom_histogram(aes(x = vote_share), binwidth = 1) +
  # xlim(-1,1) +
  theme_minimal()

ggplot(anti_incumbent_vote) +
  geom_histogram(aes(x = emigration_election_year_per_1000)) +
  # xlim(-1,1) +
  theme_minimal()
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Truncate Vote Change
# Models using ratios
cutoff <- 0.5
anti_incumbent_vote_truncated <- anti_incumbent_vote %>% 
  dplyr::filter(vote_change > cutoff | vote_change < cutoff * -1)

lm_truncate_vote_change <- feols(vote_change ~
                                   ratio_schools +
                                   ratio_hospitals +
                                   ratio_third_places +
                                   emigration_election_year_per_1000 +
                                   remittances +
                                   gdp | 
                                   nuts2016 + year,
                                 data = anti_incumbent_vote_truncated)

# Truncate Vote Share
anti_incumbent_vote_truncated <- anti_incumbent_vote %>% 
  dplyr::filter(vote_share < 30 & vote_share > 5)

lm_truncate_vote_share <- feols(vote_change ~
                                  ratio_schools +
                                  ratio_hospitals +
                                  ratio_third_places +
                                  emigration_election_year_per_1000 +
                                  remittances +
                                  gdp | 
                                  nuts2016 + year,
                                data = anti_incumbent_vote_truncated)

# Truncate Emigration Rate
anti_incumbent_vote_truncated <- anti_incumbent_vote %>% 
  dplyr::filter(emigration_election_year_per_1000 < 2)

lm_truncate_emigration_rate <- feols(vote_change ~
                                       ratio_schools +
                                       ratio_hospitals +
                                       ratio_third_places +
                                       emigration_election_year_per_1000 +
                                       remittances +
                                       gdp | 
                                       nuts2016 + year,
                                     data = anti_incumbent_vote_truncated)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
modelsummary(list(lm_truncate_vote_change, lm_truncate_vote_share, lm_truncate_emigration_rate),
             title = "DV: Incumbent's Change in Vote Share",
             coef_map = c(ratio_schools = "Children per School",
                          ratio_hospitals = "People per Hospital",
                          ratio_third_places = "People per Third Places",
                          emigration_election_year_per_1000 = "Emigration Rate between Election Years per 1000 People",
                          gdp = "GDP"),
             stars = T)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Truncate Vote Change
# Models using number of institutions
cutoff <- 0.5
anti_incumbent_vote_truncated <- anti_incumbent_vote %>% 
  dplyr::filter(vote_change > cutoff | vote_change < cutoff * -1)

lm_truncate_vote_change <- feols(vote_change ~
                                   schools +
                                   hospitals +
                                   third_places +
                                   emigration_election_year_per_1000 +
                                   remittances +
                                   gdp | 
                                   nuts2016 + year,
                                 data = anti_incumbent_vote_truncated)

# Truncate Vote Share
anti_incumbent_vote_truncated <- anti_incumbent_vote %>% 
  dplyr::filter(vote_share < 30 & vote_share > 5)

lm_truncate_vote_share <- feols(vote_change ~
                                  schools +
                                  hospitals +
                                  third_places +
                                  emigration_election_year_per_1000 +
                                  remittances +
                                  gdp | 
                                  nuts2016 + year,
                                data = anti_incumbent_vote_truncated)

# Truncate Emigration Rate
anti_incumbent_vote_truncated <- anti_incumbent_vote %>% 
  dplyr::filter(emigration_election_year_per_1000 < 2)

lm_truncate_emigration_rate <- feols(vote_change ~
                                       schools +
                                       hospitals +
                                       third_places +
                                       emigration_election_year_per_1000 +
                                       remittances +
                                       gdp | 
                                       nuts2016 + year,
                                     data = anti_incumbent_vote_truncated)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
modelsummary(list(lm_truncate_vote_change, lm_truncate_vote_share, lm_truncate_emigration_rate),
             title = "DV: Incumbent's Change in Vote Share",
             coef_map = c(schools = "Number of Schools",
                          hospitals = "Number of Hospitals",
                          third_places = "Number of Third Places",
                          emigration_election_year_per_1000 = "Emigration Rate between Election Years per 1000 People",
                          gdp = "GDP"),
             stars = T)
```