## Conclusion

<!-- Summary of thesis -->
This thesis sets out to identify emigration-induced service cuts that decrease incumbent support in Poland and Romania. I build upon findings by @dancygierEmigrationRadicalRight2022 who identify a causal chain between emigration and support for populist and radical right (PRR) parties in Sweden. The authors put forward the idea that emigration causes service cuts, which in turn cause grievances amongst the electorate. This then leads to an increase in PRR support. As possible future research, the authors suggest identifying specific service cuts that fit into their causal chain.

I apply @dancygierEmigrationRadicalRight2022’s causal chain to subnational NUTS regions in Poland and Romania. Both states experienced an increase in external emigration after joining the European Union and gaining access to Freedom of Movement (FoM). Examining Poland and Romania in this context enables to examine a potential impact FoM has on *sending* countries. This is important because the effects of emigration on Central and Eastern European (CEE) EU member states is a blind spot in political science research.

While @dancygierEmigrationRadicalRight2022 focus on PRR support, I argue for a more general approach. I examine instead the change of incumbent support associated with service cuts. I identify three service cuts that have the potential to decrease incumbent support. These are primary school closures, hospital closures and the closure of third places, i.e., bars and cafés. I measure service cuts as the average change of people per institution between two national parliamentary elections. E.g, the yearly change in number of children per primary school averaged between two elections. I argue that service cuts lead to an increase of people per institution, which impedes service quality, creating grievances and thus contributing to a decrease in incumbent support.

Using data provided by the European NUTS-level election dataset [@schraffEuropeanNUTSlevelElection2023], the V-Party Dataset [@staffani.lindbergetal.VPartyDatasetV22022], Eurostat and the statistical offices of Poland and Romania, I first examine possible associations between external emigration, incumbent support and service cuts. Results from these preliminary explorations provide promising results for Romania. In a next step, I build two-way fixed effects linear regression models to uncover an association between incumbent support and service cuts in Romania. The overall results are mixed, and the hypotheses that put forward an association between service cuts and incumbent support are rejected. However, results from the models hint at a possible association between emigration induced school closures and loss of incumbent support. In order to verify this finding, further research is needed.

<!-- Interpreting results in the broader context of further European integration -->
This thesis shows that Romania’s access to FoM is associated with higher emigration, which in turn is associated with a change in voting behaviour. This highlights that migration within the EU, one its fundamental freedoms, has an impact on receiving *and* on sending countries, such as Romania. The impact on sending countries influences who is in power and thus shapes politics on a national and supranational level.

We can observe that higher levels of external emigration are associated with a decrease in incumbent support. Incumbent parties in a candidate EU member state should take this into account when going forward with their membership application. Incumbent parties are well advised to prepare for an FoM-induced outflux in order to dampen its impact and minimise the potential emigration induced decrease on incumbent support. This can be achieved by implementing policies that incentivise returns, e.g., by giving tax breaks to citizens who return home after having studied or gathered work experience abroad.

Focusing on schools, and assuming an association between their closures and external emigration, a reduction in schools can detrimentally affect the education system. A decrease in school numbers could have serious long-term effects, potentially resulting in a generation receiving a substandard education due to FoM-induced emigration. This educational shortfall can impact job prospects, fuelling grievances that contribute to Euroscepticism later on. Therefore, it is in the EU’s own interest to address these negative and anti-EU sentiments, which ironically arise from a key EU principle, FoM. This issue could be mitigated through EU-level policies aimed at investing in the education system in regions affected by emigration. Providing for a certain educational standard will have a positive impact on future job prospects. Furthermore, educational investments should prevent school service cuts, thus eliminating the risk of citizens developing grievances in this context.

<!-- Thesis Limits -->
This thesis contains several limitations that can be addressed in future research. First and foremost is the fact that many factors can influence incumbent support aside from the service cuts identified here. Causality is never this simple and there may be a mediating factor in the causal mechanisms, which can be further explored in future research.

Second, this thesis strongly simplifies the flow of emigration. [@kingMindGapIntegrating2010 1623] shows that external emigration can occur in multiple steps, e.g. first internally from rural to urban areas, then from urban areas to another country. Internal emigration is not taken into account in this thesis, potentially skewing emigration rates in urban NUTS3 regions. Focusing on external emigration was a conscious design decision in order to measure the impact of FoM, however there is an argument to be made that the effect on the people left behind is no different between internal and external emigration. They are, in both cases, being left behind.

Third, in the preliminary analyses, Poland and Romania displayed large differences across all results. This could be an indication that the examined effects of emigration on incumbent support and service cuts may be specific to a country. This would mean that no broad, pan-CEE EU member state generalisation is possible or perhaps even sensible, due to cultural and historical differences. Future research could attempt to identify further service cuts, potentially uncovering country specific factors.

Fourth, this thesis does not consider *who* is leaving. I do not take into account an emigrant’s level of income [@dancygierEmigrationRadicalRight2022 11] or education. Regions that see emigration of high income individuals will experience higher losses of tax revenues than regions with low income emigrants. Taxes pay for services provided by the state, thus a loss of a state’s income will impact which services are cut back, influencing incumbent support.

Fifth, the models do not contain data on grievances in a region. This would make the model more complete when following @dancygierEmigrationRadicalRight2022’s approach. However, NUTS-level longitudinal data on grievances in CEE EU member states are not readily available and must be either gathered in surveys or replaced with a proxy variable.

Sixth, the interaction coefficient results in Table \@ref(tab:results-emigration-incumbent-vote-share-control-interaction) may lack statistical power due to noise that occurs when using interactions [@gelmanYouNeed162018]. In order to counter this problem, more observations are needed, e.g., data covering a longer time period. When collecting further observations, it could be of interest to obtain more electoral data too, as the data provided by @schraffEuropeanNUTSlevelElection2023 only cover one election occurring before EU accession. Pre-accession electoral data would provide the opportunity to compare the effect of emigration on incumbent support *before* the introduction of FoM, yielding further insights.

Finally, as mentioned on p. \pageref{passage:volatility-issue}, volatility may have been operationalised incorrectly. All results show a positive coefficient, indicating that higher levels of volatility are associated with higher levels of incumbent support. This is not an intuitive result and may be due to the simplified method of how party changes are dealt with when calculating the Pedersen Index (see p. \pageref{passage:electoral-volatility}). Future research could implement a more nuanced approach when handling party changes or when controlling for electoral volatility.

<!-- Future research -->
Based on the findings presented here, there are several avenues of future research. E.g., does incumbent party orientation play a role in the context of emigration induced service cuts? I assume that party orientation has an influence on how much and which services are cut back, thus having different impacts on the electorate. Also, does party orientation have an effect on emigration? E.g., do more people emigrate if PRR parties are in power?

Another potential future avenue is examining the long term effect of emigration induced school closures on the electorate. This can help understand how far reaching the impact of FoM is in a sending country. However, these panel data probably do not exist yet, but could be of interest once school aged children from the 2010s become of voting age in the 2020s.

Finally, further effects of emigration on sending countries beyond service cuts should be examined. Does emigration impact democratic institutions, social cohesion or other factors? Answering these questions can help obtain a bigger picture of the extent of FoM on sending countries.
