---
title: "Research Proposal MA Thesis: Emigration and Voting Behaviour in Central and Eastern European EU Member States"
author: "Fabian Aiolfi"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    extra_dependencies: "microtype"
bibliography: references.bib
classoption: a4paper
lang: en-UK
header-includes:
   - \usepackage{hyperref}
   - \usepackage{setspace}
   - \onehalfspacing
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abstract
[1000 characters]

## RQ
Why does emigration from CEE EU member states cause vote switching amongst the voters left behind?

###############

## Introduction
`Central problem / puzzle that thesis will address`
- CEE countries show high levels of emigration (numbers, source)
	- 2017 Ubareviciene: Since the 1990s, lithuania lost almost one-quarter of its population, and some regions within the coun- try lost more than 50% of their residents. 
	- 2018 Vasilopoulou: The key drivers of intra-EU migration were economic, related to labour market factors, with EU migrants moving abroad to seek better job opportunities
	- Potential preliminary explorations
		- is there a correlation between end of Freedom of Movement-transitional period and increase in external migration? → if yes, this would help this thesis’ case of the EU’s effect on emigration in CEE → see job vacancy stats https://ec.europa.eu/eurostat/web/labour-market/database; see also employment rate https://ec.europa.eu/eurostat/web/lfs/database; perhaps use GDP per capita and then control for unemployment rate, social welfare benefits index, quality of life index, political stability (via ChatGPT); also take into account distance between countries (see 2001 Gleditsch); https://en.wikipedia.org/wiki/Freedom_of_movement_for_workers_in_the_European_Union#Summary; panel data model? https://towardsdatascience.com/a-guide-to-panel-data-regression-theoretics-and-implementation-with-python-4c84c5055cf8; https://www.youtube.com/watch?v=T7Dmp8a7IU0

	- also 2016 FT
- Emigration has profound effects in the sending countries. E.g. lack of labour, population decline;
	- also affects individuals, e.g. through a sense of loss, anger or distress (2012 Marchetti‐Mercer); 2019 Ivlevs: We also document that having household members abroad is linked with increased stress and depression, which are not offset by remittances → In short: emigration leaves no one indifferent
	- 2009 Thaut for specific country case
- The EU’s freedom of movement makes emigration easier, magnifying the effects of emigration
- How does emigration effect the people left behind? Does emigration change their voting behaviour?
- Emigration correlates with vote switching → There exists a negative significant (p<0.05) correlation between average migration and vote switching: The lower the average migration, the more vote switchers in the NUTS3 region
	- [Display data and findings]
- RQ:
	- ==Why does emigration from CEE EU member states cause vote switching amongst the voters left behind?==
	- Why does international emigration from CEE EU MS cause vote switching amgonst voters in sending countries?

`Describe causal mechanism`
- @dancygierEmigrationRadicalRight2022
	- ==emigration → service cuts → grievances → PRR voting==
- [@dancygierEmigrationRadicalRight2022, p. 35]: do not show what exactly causes a change in voting behaviour; future research should look into what type of service cuts lead to PRR voting
- [briefly describe watershed moments; also add EU ascension as further watershed moment, or rather when CEE citizens were allowed to work/live in other EU MS]
	- [describe updated causal mechanism? with “watershed moment” after “service cuts”]

`Why is it worth studying?`
- migration has been studied at the receiving end, but the sending end hasn’t been studied enough yet (2022 Kyriazi)
	- 2012 Marchetti‐Mercer p. 378: “Toyota, Yeoh, and Nguyen (2007) argue that globally far more people are “left behind” than emigrate, but those left behind are often forgotten by research.”
	- 2020 bruzelius p. 2: “FoM not just involves the right to enter, but also the right to exit” 
- understanding political behaviour on a national and supranational level
	- how does emigration affect voting behaviour?
	- FoM is a foundational aspect of European integration and affects emigration. Important to understand the effects of FoM on voting behaviour in lieu of European Integration
- effects of FoM in CEE is understudied
	- 2012 pfutze looks at mexico, but can the same results be expected in EU?
	- 2017 Barsbai looks at moldova, but moldova is not in the EU thus emigration has a different backdrop

`caveats / limitations`
- approximation of effect on voting behaviour
	- difficulty of disentangling individual voting behaviour affected by emigration; 
	- lack/not a lot of individual level data


## The state of the field

==Why does emigration from CEE EU member states cause vote switching amongst the voters left behind?==

```
Present and discuss the answers that the available literature offers to your RQ
1. what we already know and what we do not yet know about your research question
2. how your work will build on previous research
```

- I’m working under the basic assumption that emigration causes vote switching
- the following literature shows this

- Emigration has been shown to affect voting behaviour and electoral outcomes in a wide range of spatial and temporal contexts: From 19th century Sweden (2017 Karadja) to Mexico at the start of the 21st century (2014 Pfutze).

- Emigration can affect electoral outcomes in two ways.
- First, emigration can change the composition of the electorate. 2022 Lim shows that emigrants from CEE are disproportionately younger, cosmopolitan and politically progressive populations, resulting in a remaining population that is older and more conservative. They then vote accordingly. However, with respect to my research question, this does not necessarily *change* their voting behaviour, it only makes their voting more common.

- Second, emigration can affect the electoral preferences and the voting behaviour and thus trigger vote switching amongst the people left behind.

- On the one hand, emigration can affect political behaviour indirectly by altering a voter’s overall wellbeing
- Family members of neighbors of emigrants have a higher life satisfaction and budget easing through remittances, but suffer from more depression and stress (2018 Nikolova) and are more prone to psychological distress (Marchetti-Mercer 2012 in 2022 lim)

- On the other hand, emigration can affect political behaviour directly
- A wide range of literature explains how emigration causes a decrease in political interest. This can be caused by a decrease in political mobilisation and collective action (2019 Sellars), a decrease in civic engagement (2008 Goodman / Bravo, Jorge, 2007), opposing voices leaving and thus resulting in a quiescent electorate (2022 Peters) or through a loss of political actors (2022 Lim).
- Despite this decrease in political interest, some remainers still vote. If the number of people voting shrinks, then it becomes all the more important that we understand how the remaining voters are affected by emigration and how they thus cast their ballot, because a smaller electorate wields more power (?)

- Why it is important is shown e.g. by 2017 Barsbai, who reveals a negative effect between emigration and votes for the Communist Party in the Moldovan elections of 2009 and 2010. Elections during those years brought significant political change to the ex-soviet country (2017 Barsbai, p. 41), because voters switched away from the Communist Party, who had gained electoral power in previous elections. Voters switched because western social norms and political preferences diffused amongst the electorate through emigration (p. 66).

- Another reason why emigration is important is because some research uncovers links between emigration and voters switching to populist and radical parties (@dancygierEmigrationRadicalRight2022, 2022 Lim, 2020 Otteni)
- However, there are two reasons why this link between emigration and radical parties can be questioned
- First, 2020 Mercator and 2023 Schütze provide mixed results of this claim, showing that emigration induced support for these parties is only given under certain conditions
- Second, there is a point to be made that non-extreme parties, e.g. a mainstream opposition party, may also benefit from emigration.
- A voter does not necessarily have to cast a ballot for an extreme party. Instead they can simply critique the incumbent government or status quo parties if emigration becomes politicised (mercator 2020)
- Voters receive remittances which realigns their party preferences closer to their personal ideological preferences (2012 pfutze). This does not necessarily have to be an extreme party. 
- People will not cast a vote for a extreme party if there is no extreme party on the ballot.
- In a specific case, 2023 Schütze shows how regional out-migration does not lead to a higher voting preference for the AfD, a German right-wing populist party. However, this study only takes intra-German emigration (from east to west) into account, not external/international emigration
- For these reasons and due to the mixed empirical results, I will look into vote switching in general and not focus on voting for radical right parties

- @dancygierEmigrationRadicalRight2022 uncovers a correlation between emigration and the rise of Populist Radical Parties (PRR). The authors suggest that emigration decreases an area's quality of life, e.g., through cuts in public services.
- These service cuts create grievances amongst voters.
- These grievances then affect voting behaviour: Voters turn against incumbents and cast a ballot for PRR parties.
- As a side note, I argue that these grievances are different to the ones described by 2018 Nikolova. Nikolova’s grievances are personal/intimate, caused by family matters. Dancygier’s grievances are less intimate and of a more general and economic nature. Because they are less intimate, I argue that a person is more likely to voice them public, e.g. by changing their voting behaviour.
	- This claim is supported by 2014 Kapur, who underlines the importance of understanding the reason behind a person’s emigration. Emigration from CEE EU MS is primarily an economic matter (2018 Vasilopoulou), thus I assume the grievances of the people left behind to be closely linked to economic factors and less to family matters

- The causal mechanism according to @dancygierEmigrationRadicalRight2022 can be summarised as follows:

$$Emigration \rightarrow Service \; Cuts \rightarrow Grievances \rightarrow Vote \; for \; PRR$$

- However, the authors do not show which service cuts lead to cause grievances, thus influencing a voter’s behaviour that leads them to cast a vote for PRR parties [@dancygierEmigrationRadicalRight2022, p. 35]. They leave this aspect open for future research.
- My aim is to figure out what these service cuts are and describe this in the next section (under the assumption that it causes general vote switching, not necessarily a vote for a PRR party)


## The project description (what?)

`theory: what would we expect to happen based on theory?`
- Voters evaluate a government’s past performance and their policy outcomes (1966 Key, p. 9, p. 58-59, p. 61). They vote retrospectively.
- Service cuts, especially public ones, will give the incumbent government a poor performance record in the eyes of the voter.
- This will increase the likelihood that the voter switches party, away from the incumbent, towards another party.

`Make explicit the causal mechanism`

- Based on @dancygierEmigrationRadicalRight2022’s assumption that service cuts lead to grievances that then lead to PRR voting, this thesis asks the following question: Which emigration induced service cuts cause grievances?

- preliminary exploration: measure grievances through ESS5, 9: How happy are you? → correlation between happiness and emigration → are people from emigration-high regions generally unhappier?

- preliminary exploration: demographic change in emigration hit regions → less younger, more older → less schools, less hospitals

- preliminary exploration: grievances and vote switching? is there a correlation between the two in general, and more so in the actual regions that are hit by emigration? → might be difficult because EES does not ask about happiness → combine EES and ESS?; or maybe Q20 “And over the next 12 months, how do you think the general economic situation in Ireland will be?”

- To answer this question, I suggest the following approach
- As the figures from the preliminary exploration `02_fom_emigration` show,  emigration is a slow yet steady attrition of a country, that started long before a country’s accession to the EU.
- Due to the gradual nature of steady emigration, it goes largely unnoticed to the individual who remains. However, there comes a point where the impact of emigration on a region reaches a tipping point, causing a watershed moment amongst its inhabitants. In this watershed moment, the people who have remained suddenly realise the impact emigration is having on their region. I regard these watershed moments as critical turning points in the lives of the remaining population. They can lead to dissatisfaction with existing conditions and a sense of reduced community belonging, leading to a change in their voting behaviour.

- I will examine three possible watershed moments that I believe significantly influence the voting behaviour of the remaining residents. 

- The first moment is the closing of local primary and secondary schools.
- Schools contribute towards community feeling [@sagemanSchoolClosuresRural2022]. Closing a school will reduce a community's cohesion and negatively impact the lives of families with school-aged children. They must either travel further to reach the next school or must put up with classes that have increased in size due to the consolidation of schools.

- The second watershed moment is the closing of hospitals. Because emigrants tend to be younger [@limElectoralConsequencesInternational2023, p. 39], the remaining population is likely to be older. The elderly are more reliant on hospitals, thus I argue that a hospital closure can cause distress and thus grievances amongst the remaining population.
- hospital closings and emigration are also linked: emigration of medical doctors and other healthcare professionals is a problem in CEE (2020 Mercator, https://www.theguardian.com/world/2019/apr/21/romanian-hospitals-in-crisis-as-emigration-take-its-toll)
- Schools and hospitals closing in emigration-hit regions in Sweden are topics that newspapers reported on [@dancygierEmigrationRadicalRight2022, p. 32]. This indicates that there may exist a link between these closures and grievances.

- Schools and hospitals closings are services made available by the state. In contrast, the third and final watershed moment will look at a service cut in the private sector, namels the decrease in the number of public spaces that act as "third places".
- These are local "informal public gathering places" that foster community building [@oldenburgGreatGoodPlace1999, p. 16], e.g., cafés, bars and restaurants. Their closure can erode a communal sense of belonging and push people towards populist parties [@boletDrinkingAloneLocal2021].


```
Operationalize key terms by defining them in terms that can be measured or observed. Good (maybe not ideal) indicators are those available, close to the concept you want to measure, and widely accepted. The more indicators you have, the more solid your proposal will be.
```

Based on this causal chain of events:
Emigration → Service Cuts → Grievances → Vote Switching

I set up this regression formula:
Share of Vote Switchers = Service Cuts + [External Emigration + Grievances + Economic Factors + Remittances]

- A variable always covers a NUTS3 region in 1 year (e.g. HR035 in 2014)
- Share of vote switchers: Proportion of voters who “moved across party lines” (1966 Key, p. 16) between two national elections compared to all voters
- Service Cuts, the main independent variable, are operationalised as ratios to its target audience:
	- number of children to schools in a region
	- population size to number of hospitals in a region
	- number of third places (cafés, bars, restaurants) to population size in a region

**Control Variables**
- external emigration from a region = international emigration (spurred on by FoM? depends on results from preliminary exploration)
- received remittances in a region (see 2012 Pfutze)
- economic factors, e.g. unemployment, nuts3 gdp per capita
	- I assume that a region's overall socioeconomic climate will impact the perception of the described closures. Inhabitants of a region that is worse off will develop stronger grievances due to the watershed moments described above. This in turn will have a stronger affect on voting behaviour.
- other / TBD
	- transitional period between EU accession and end of FoM transitional period (https://en.wikipedia.org/wiki/Freedom_of_movement_for_workers_in_the_European_Union#Summary); unclear how to measure this: number of countries won’t do it, somehow measure economic attractiveness / pull of a country?


`hypotheses as a general answer to the puzzle`

→ in general: a higher ratio (more children in one school, more people for one hospital, more people for one third place) leads to higher vote switching






**Public service cuts**
H1: A higher ratio of children to schools in a region leads to a higher likelihood of vote switching in that region.
*Emigration → Change in age distribution*

H2: A higher ratio of seniors to hospitals in a region leads to a higher likelihood of vote switching in that region.
*Emigration → Population decline, labour shortage*

**Private service cuts**
H3: A higher ratio of people to third places in a region leads to a higher likelihood of vote switching in that region.
*Emigration → Population decline, labour shortage*


`define key terms`
- …




`intervening conditions?`
`We would also strongly recommend that you explicitly specify the existence of any intervening conditions that - at the very least - change the production of the expected effects and - at most - need to be present for the hypothesized relations to hold.`



## The research design (how, where and when?)

`List research operations: Why are they best to tackle RQ?`
- …
- differentiate between internal and external migration: external migration linked to EU through FoM

`justify case selection of geographical and temporal span: what's their logic and are there disadvantages?`
- I aim to take Dancygier et al.'s idea of emigration causing grievances and apply it to voters changing their voting behaviour in Central and Eastern European (CEE) EU member states. I pick these countries because they are strongly affected by emigration, which has also been spurred on by the EU's freedom of movement (→ check if assumption holds!)
- aim: examine voting behaviour at NUTS3 level, as different regions are affected differently by emigraiton

`methodology`
…

`data`
- nuts level migration data: CNMIGRATRT: https://ec.europa.eu/eurostat/databrowser/view/DEMO_R_GIND3__custom_7113680/default/table?lang=en
- NUTS3 level electoral results are provided by the \underline{\href{https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/IQRYP5}{EU-NED European NUTS-Level Election Dataset}}. → perhaps add a table showing how many missing values there are, showing how “unbalanced” the data is?
- Data on school closings is available through the \underline{\href{https://podaci.dzs.hr/en/statistics/education/basic-and-upper-secondary-schools/}{Croatian Bureau of Statistics}}.
- internal and external migration: national stats websites


## Conclusion
```
- alluding to the original research question, reminding the reader about the main theoretical claim (in normative works)/falsifiable hypothesis (in empirical ones)
- speculating on the final product of the thesis: what kind of impact could your research have if it is successful?
```

In sum, I aim to isolate specific causal mechanisms to better understand how emigration-induced service reductions influence the success of political parties. By doing this, I will provide further insights into the dynamics between emigration spurred on by the EU's freedom of movement, community disintegration and political outcomes.



#################



## In Development

### Theory

I am currently considering two theories to help answer my research question. The first is the political opportunity theory. @eisingerConditionsProtestBehavior1973 explains why riots in the US in the 1960s varied between cities. He concludes that some citizens were unable to voice their complaints legally because they lacked political opportunity. These people were thus more likely to riot. Applied to my research question, this theory would help explain which parties a voter would turn to if the voter is unhappy with the incumbent. Opposition and populist parties could capitalise on a voter's grievances and present themselves as alternatives to the status quo.

The second possible theory is issue voting. @keyResponsibleElectorateRationality1966a describes how voting behaviour is influenced by salient issues. I expect the aforementioned watershed moments to be of high salience for voters, thus influencing their vote choice.

\newpage

## References
```
This should be focused and updated but sufficiently comprehensive and grounded in classics.
```
