## Project Description

<!-- theory: what would we expect to happen based on theory? -->
@keyResponsibleElectorateRationality1966a states that voters evaluate a government’s past performance and their policy outcomes [@keyResponsibleElectorateRationality1966a 35, 58–59, 61]. They vote retrospectively and their voting behaviour is influenced by salient issues [@keyResponsibleElectorateRationality1966a 73], such as the described service cuts. These cuts affect citizens’ daily lives and cause grievances. 

Such cuts, especially cuts to public services, cause grievances amongst voters and will give the incumbent party a poor performance record. Grieving voters that are dissatisfied with the incumbent party will not support them in the next election [@bowlerStrategicProtestVoting, 489].

<!-- Make explicit the causal mechanism -->
Based on @dancygierEmigrationRadicalRight2022’s assumption that service cuts lead to grievances which then lead to PRR voting, this thesis asks the following question: Which emigration-induced service cuts have a negative impact on the sending country’s incumbent vote share?

<!-- Insert somewhere here: 2022 Dancygier p. 2: Emigration can thus adversely affect public and private services, leading to school and business closures and straining the viability of public transport and healthcare systems. Additionally, those who remain may suffer psycho- logically, feeling that emigration devalues the status of their hometowns and communities. The accompanying decline in services and gathering places further saps community spirit. See also p. 7! -->

@dancygierEmigrationRadicalRight2022 [2] state that emigration is linked to service cuts such as schools and business closures. Also, emigration strains the healthcare system. Based on this, I assume that emigration has a negative effect on the number of schools, the number of hospitals and the number of “third places”^[“Third places” are local "informal public gathering places" that foster community building [@oldenburgGreatGoodPlace1999 16], e.g., cafés, bars and restaurants.] Following @dancygierEmigrationRadicalRight2022’s theory, I assume that a decrease in the number of these institutions causes grievances amongst the remaining population for the following reasons.

Schools contribute towards community feeling [@sagemanSchoolClosuresRural2022 964]. Closing a school will reduce a community's cohesion and negatively impact the lives of families with school-aged children. They must either travel further to reach the next school or must put up with classes that have increased in size due to the consolidation of schools.

Hospitals are important for populaiton who do not emigrate. Because emigrants tend to be younger [@limElectoralConsequencesInternational2023 39], the remaining population is likely to be older. The elderly are more reliant on hospitals, thus I argue that a hospital closure can cause distress and thus grievances amongst the remaining population. Hospitals closures in CEE are spurred on by the emigration of medical professionals [@vorlanderMIDEM2021Emigration2021 13; @walkerRomanianHospitalsCrisis2019]. 

To underline the importance of school and hospital closings, @dancygierEmigrationRadicalRight2022 [32] show how newspapers report on such closings in Swedish emigration-heavy regions. This indicates that there may exist a link between these closures and grievances.

Schools and hospital closings are services made available by the state. In contrast, “third places” are supplied by the private sector. Their closure can erode a communal sense of belonging and push people towards populist parties [@boletDrinkingAloneLocal2021 1653].

Does emigration cause these service cuts? In order to show that these cuts are not only due to austerity measures or a state’s neo-liberal tendencies, I perform a brief exploratory data analysis showing that emigration and the three mentioned service cuts correlate.

<!-- preliminary exploration
- correlation between emigration and these service cuts
	- Deskriptive Analyse?
	- Bivariater Zusammenhang zwischen Emigration und Rückgang von öffentlichen Diensten wie Schul- und Spitalschliessungen
	- Z.B. Anzahl Ärzte, Anzahl Kinder
--> 

This is the updated causal chain of events, based on the causal chain displayed in (\ref{eq:cm_dancygier}):

\begin{equation}
Emigration \rightarrow Service \; Cuts \rightarrow Grievances \rightarrow Anti-Incumbent \; Vote
\label{eq:cm_updated}
\end{equation}

<!-- operationalisation, model specification --> 
Based on this causal chain, I set up the following empirical specification:
…

<!--
\begin{equation}
\begin{aligned}
Incumbent \; Vote \; Change_{i,j} = \beta_0 & + \beta_1Service \; Cuts_{i,j} \\
      & + \beta_2External \; Emigration_{i,j} \\
      & + \beta_3Economic \; Factors_{i,j} \\
      & + \beta_4Remittances_{i,j} \\
      & + \varepsilon 
\end{aligned}
\end{equation}
<!-- https://latexeditor.lagrida.com/ --> 

<!-- adjust t1 and t0 years here, $j$ doesn't work anymore. also includes vote switching  --> 
- $i$ indexes a NUTS3 region in the year $j$. The dependent variable is the change in vote share between two national elections.
- I will measure individual level vote switching using the European Election Study (EES, @ZA7581).^[If a respondent’s answer to question 9 is not the same party as the highest rated party in question 10, then they are labelled a vote switcher. From the European Parliament Election Study 2019 Irish Country Questionnaire [@ZA7581]:
Question 9: “Which party did you vote for at the Irish General Election of 2016?” 
Question 10: “We have a number of parties in Ireland each of which would like to get your vote. How probable is it that you will ever vote for the following parties? Please answer on a scale where 0 means “not at all probable” and 10 means “very probable”.”]
--> 

Service Cuts, the main independent variable, are operationalised as ratios to their respective target audiences. The first service cut is the ratio of children per school in a region. The second is the ratio of people to hospitals in a region. The third is the ratio of people to third places (cafés, bars, restaurants) in a region.

<!-- Control Variables --> 
I will control for the following variables. First, external emigration from a region, which entails the crude number of citizens emigrating abroad from the region. Second, I take the inflow of remittances in a region, because remittances can realign a voter’s party preferences in favour of ideological preferences, thus changing their voting behaviour [@pfutzeDoesMigrationPromote2012a 161]. Third, I control for general electoral volatility. CEE states show higher levels of electoral volatility that states in Western Europe, Latin America or the United States (Epperly, 2011, p. 831). This volatility most often hits incumbent parties in government (Bochsler, 2019, p. 1). To understand emigration's influence on anti-incumbent voting, I must account for this volatility. Powell (2014, p. 139, 143) shows that economic downturns, specifically shifts in GDP since the fall of Communism, lead to a higher likelihood of the electorate switching to a new party. This observation aligns with Bertus's 2022 study, highlighting that in smaller Hungarian settlements, socioeconomic dynamics and labor market conditions explain electoral shifts (p. 77). Therefore I will incorporate controls for economic performance to single out the impact of emigration on anti-incumbent voting.

<!-- Hypotheses as a general answer to the puzzle --> 
As a general relation between dependent and independent variables, I assume an increase in service cuts, e.g., more children per school, leads to a higher share of anti-incumbent votes. I define the following three hypotheses:

<!-- Public service cuts --> 
<!-- Emigration → Change in age distribution --> 
**H1**: A region’s increase of children per school leads to an increase in the region’s anti-incumbent vote.

<!-- Emigration → Population decline, labour shortage -->
**H2**: A region’s increase of seniors per hospital leads to an increase in the region’s anti-incumbent vote.

<!-- Private service cuts -->
<!-- Emigration → Population decline, labour shortage -->
**H3**: A region’s increase of citizens per “third places” leads to an increase in the region’s anti-incumbent vote.

<!--
`define key terms (or use concepts that everyone in political science uses)`

`intervening conditions?`
`We would also strongly recommend that you explicitly specify the existence of any intervening conditions that - at the very least - change the production of the expected effects and - at most - need to be present for the hypothesized relations to hold.`
-->