## Research Design
<!-- The research design (how, where and when?) -->
<!-- List research operations: Why are they best to tackle RQ? -->

I differentiate between internal and external migration and focus on the latter, as I want to examine the effect of the EU’s FoM on emigration and voting behaviour.

I will measure the effect of service cuts on a subnational, NUTS3 level, data permitting. I do this for the following two reasons. First, measuring subnational regions instead of countries will increase sample size and thus provide more accurate results. Second, regions within countries have different levels of emigration (see Figure \ref{fig:net_migration_map}), allowing for differentiated measurements.

<!-- operationalisation --> 
I measure $Anti{\text -}Incumbent \; Vote$, my dependent variable, by examining the vote share loss experienced by the incumbent party after they assume power. To achieve this, I calculate the difference between the incumbent party's vote share in the subsequent election $t1$ and their vote share in the initial election $t0$ where they first gained power.

$Service \; Cuts$, the main independent variable, are operationalised as ratios to their respective target audiences. The first service cut is the ratio of children per school in a region. The second is the ratio of people to hospital beds in a region. The third is the ratio of people to “third places” in a region.

I operationalise $Electoral \; Volatility$ by taking a region’s economic performance into account. @powellRevisitingElectoralVolatility2014 [139, 143] show that economic downturns, specifically shifts in GDP since the fall of Communism, lead to a higher likelihood of the electorate switching to a new party. This observation aligns with @bertusGeographyElectoralVolatility2022’s study, highlighting that in smaller Hungarian settlements, socioeconomic dynamics and labor market conditions explain electoral shifts [77]. Therefore I will incorporate controls for economic performance to single out the impact of emigration on anti-incumbent voting.

<!-- justify case selection of geographical and temporal span: what's their logic and are there disadvantages? -->

I will examine CEE EU member states because emigration in this region has not been studied in detail and because I see an opportunity to measure the political impact of FoM on the region. In order to measure an effect of a country joining the EU, I will focus on a time span around the country’s accession, e.g., ten years before and after joining, if data are available for the time span. The time span will only go up to and include the year 2019, because I assume the COVID-19 pandemic to have a strong influence on emigration in 2020 and beyond.

A potential disadvantage of the case selection could be cultural differences between CEE EU member state NUTS3 regions, leading to inaccurate results. I have chosen a very broad definition of CEE countries, possibly making a comparison between regions difficult. It may make sense to narrow down the selection, e.g., by excluding the three Baltic states. A further disadvantage is missing data in emigration time series and a lack of individual level data at NUTS3 level.

<!-- Methodology -->
I will use quantitative methods to answer my research question. In order to gain a general overview, I will perform a subgroup analysis, e.g., by analysing NUTS3 regions within a country. I will then build simple regression models that uncover potential correlations between emigration and anti-incumbent voting. Data quality permitting, I can then focus on regions that show promising results.

Such a focus may involve mediation analysis. Due to the chain of causal events described in (\ref{eq:cm_updated}), service cuts act as a mediator between emigration and anti-incumbent voting. This analysis can help explain how the three service cuts influence anti-incumbent voting in different ways.

A further deep dive will involve applying the Regression Discontinuity Design method in order to compare regions in EU member states with regions in non-EU states, such as Albania, Bosnia and Herzegovina, Kosovo, Moldova, Montenegro, North Macedonia or Serbia. Using EU accession as the treament, this allows to measure the impact of FoM on emigration and the subsequent effects on anti-incumbent voting.
<!-- Explicitly state for which non-EU MS you have data --> 

<!-- Data -->
NUTS3 level international emigration data are provided by the national statistics agencies of the respective countries.^[See sources in Appendix 1.] As a fallback, NUTS3 level migration data is also provided by Eurostat.^[Variable: CNMIGRATRT; Online data code: DEMO_R_GIND3; Link: https://ec.europa.eu/eurostat/databrowser/view/DEMO_R_GIND3__custom_7113680/default/table?lang=en (retrieved 4 September 2023)] However, these data do not differentiate between internal and external migration.

NUTS3 level data for the dependent variable are provided by the EU-NED European NUTS-Level Election Dataset.^[https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/IQRYP5 (retrieved 5 September 2023)].

National data on schools, hospitals and “third places” are provided by Eurostat and by the national statistics agencies of the respective countries. See Appendix 2 for sources.

Data on remittances seems not to exist at NUTS3 level. As an alternative, I will use data on remittances on the national level provided by the World Bank’s KNOMAD.^[https://www.knomad.org/data/remittances (retrieved 9 October 2023)]